// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csjoczatmnsqcssdgklw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzam9jemF0bW5zcWNzc2Rna2x3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNDk5MzAsImV4cCI6MjA1MzcyNTkzMH0.uvFfOIhqW8NvTzt-1v9UHzxQND_1_3zWfSxM5TtUMqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);